name: c10-dirichlet-csgld-cpe
method: grid
parameters:
  label_noise:
    values:
      - 0
  noise:
    values:
      - 1e-6
  temperature:
    values:
      - 1
      - 1e-1
      - 1e-2
      - 1e-3
      - 1e-4
      - 1e-5
      - 3
      - 10
  seed:
    values:
      - -1
      - -2
      - -3
program: experiments/train_lik.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --dataset=cifar10
  - --likelihood=dirichlet
  - --sgld-epochs=1000
  - --sgld-lr=1e-7
  - --n-cycles=50
  - --n-samples=50
