name: ti-aug-dirichlet-csgld
method: grid
parameters:
  label_noise:
    values:
      - 0
      - .1
      - .2
      - .5
      - .8
  noise:
    values:
      - 1e-6
      - 1e-5
      - 1e-4
      - 1e-3
      - 1e-2
      - 1e-1
      - 5e-1
      - 1
  aug_scale:
    values:
      - 20
  # seed:
  #   values:
  #     - -1
  #     - -2
  #     - -3
program: experiments/train_aug_lik.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --dataset=tiny-imagenet
  - --likelihood=dirichlet
  - --sgld-epochs=1000
  - --sgld-lr=1e-7
  - --n-cycles=50
  - --n-samples=50
