name: ti-softmax-csgld-label-noise
method: grid
parameters:
  label_noise:
    values:
      - 0
      - .1
      - .2
      - .5
      - .8
  temperature:
    values:
      - 1
      - 1e-1
      - 1e-2
      - 1e-3
      - 1e-4
      - 1e-5
      - 3
      - 10
  # seed:
  #   values:
  #     - -1
  #     - -2
  #     - -3
program: experiments/train_lik.py
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --dataset=tiny-imagenet
  - --likelihood=softmax
  - --sgld-epochs=500
  - --sgld-lr=1e-6
  - --n-cycles=10
  - --n-samples=50
